version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/quiz
    ports:
      - 8000:8000
    env_file:
      - .env
    restart: "on-failure"
    depends_on:
      - db
  db:
    image: postgres:10.5-alpine
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    restart: "on-failure"

volumes:
  postgres_data:

